Benito's Italian Restaurant # your name (or website title) here
logo: ![italian](italian.jpg)

description: > # your text below (remove <br> elements if you don't need line breaks)
 Benito's Italian Restaurant: Serving Italian food that makes you feel at home!

  <br><br>
  <a href="https://jdj25.github.io/team-c-final-group/about">About</a>
  <br><br> 
  <a href="https://jdj25.github.io/team-c-final-group/blog">Blog</a>
  <br><br>
  <a href="https://jdj25.github.io/team-c-final-group/brand_journey">Brand Journey</a>
  <br><br>
  <a href="https://jdj25.github.io/team-c-final-group/subscribe">Subscribe</a>
  <br><br>
  <a href="https://jdj25.github.io/team-c-final-group/privacy_policy">Privacy Policy</a>
  
google_analytics: G-4WC9H6LY0C
