# <div align="center">Benito's Italian Restaurant</div>

<div align="center">

![italian](italian.jpg)

**Benito's Italian Restaurant**: Serving Italian food that makes you feel at home!

<br><br>

[About](https://jdj25.github.io/team-c-final-group/about)

<br><br>

[Blog](https://jdj25.github.io/team-c-final-group/blog)

<br><br>

[Brand Journey](https://jdj25.github.io/team-c-final-group/brand_journey)

<br><br>

[Subscribe](https://jdj25.github.io/team-c-final-group/subscribe)

<br><br>

[Privacy Policy](https://jdj25.github.io/team-c-final-group/privacy_policy)

</div>

google_analytics: G-4WC9H6LY0C
