title: Benito's Italian Restaurant # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Benito's Italian Restaurant: Serving Italian food that makes you feel at home!

  <br><br>
  <a href="#">About</a>
  <br><br> 
  <a href="#">Blog</a>
  <br><br>
  <a href="#">Brand Journey</a>
  <br><br>
  <a href="#">Subscribe</a>
  <br><br>
  <a href="#">Privacy Policy</a>
  
google_analytics:  # your Google Analytics tracking ID here
